version: '3.7'

services:
    backend:
        image: ghcr.io/rkorom/backendforfrontend:latest
        restart: 'always'
        depends_on:
            - database
        ports:
            - '8000:8000'
        labels:
            - 'com.centurylinklabs.watchtower.enable=true'

    watchtower:
        image: containrrr/watchtower:latest
        restart: 'always'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.docker/config.json:/config.json:ro
        environment:
            WATCHTOWER_CLEANUP: 'true'
            WATCHTOWER_POLL_INTERVAL: '300' # seconds
        command: --label-enable
volumes:
    mongodb: ~
    minio_data:
        driver: local
